name: taskulator
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  math_expressions: ^2.0.0
  curved_navigation_bar: ^0.3.3
  font_awesome_flutter: ^8.8.1
  http: ^0.12.2
  firebase_core: ^0.4.0+9
  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.12.9+5
  google_sign_in: ^4.5.3
  contacts_service: ^0.4.6
  permission_handler: ^5.0.1+1
  shared_preferences: ^0.5.10
  flutter_money_formatter: ^0.8.3
  provider: ^4.3.2+2
  timeago: ^2.0.27
  flutter_staggered_animations: ^0.1.2
  flutter_spinkit: ^4.1.2+1
  flutter_signin_button: ^1.1.0
  flutter_typeahead: ^1.8.8


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/graphics/
  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
        - asset: assets/fonts/Rubik-Bold.ttf
          weight: 700
        - asset: assets/fonts/Rubik-Light.ttf
          weight: 200
        - asset: assets/fonts/Rubik-Medium.ttf
          weight: 400































